### ISSUE TITLE
adding Schaefer parcellation values from freesurfer outputs

### ISSUE THREAD

**Issue by edickie** [TIGRLab/SCanD_project#113]
There's some info for doing this here:
https://github.com/RafaelRomeroGarcia/CBIG/blob/94a60d590994e363fb53702fe7d2bede11773bfe/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/project_to_individual/README.md?plain=1#L39

We can start with Schaefer (who have gcs files available) - then try to figure out how to make other afterward

**Comment by GhazalehManj** [comment]
Which one I should put in gcs folder:
[](https://www.dropbox.com/s/1vk6zjus5nogd0z/gcs_Schaefer2018_update20190916.zip?dl=0&e=1&file_subpath=%2Fgcs)

**Comment by edickie** [comment]
All the 7 network one's? that would match the XCP-D Scheafer outputs

**Comment by GhazalehManj** [comment]
Done.
