### ISSUE TITLE
fmriprep steps

### ISSUE THREAD

**Issue by shuwei-wu** [TIGRLab/SCanD_project#310]
Hi, I would like to know about aims of fmriprep_fit and fmriprep_apply steps that their code seems to differ only at the run level ("fit" with resample, "apply" with full). I know that in previous versions fmriprep in stage 1 and 2 corresponded to anat and func data respectively, but why not merge them into one step? Thanks.

**Comment by GhazalehManj** [comment]
Hi,
The separation of fmriprep_fit and fmriprep_apply steps improves efficiency by splitting transformation estimation and application:
- fmriprep_fit estimates transformations (e.g., anatomical alignment) without applying them, so these can be reused across multiple runs.
- fmriprep_apply uses the precomputed transformations to align functional data, saving time if only the application needs re-running.

Combining them would force recalculation of transformations each time, so separating them keeps processing flexible and faster.
