### ISSUE TITLE
add command line prompts to stage scripts

### ISSUE THREAD

**Issue by edickie** [TIGRLab/SCanD_project#53]
might be simplest to add command line prompt to all steps in stage scripts and ask user it this is appropriate

**Comment by edickie** [comment]
tutorial for bash command line prompts here
https://www.linkedin.com/pulse/part-4-input-output-bash-scripts-your-devops-guide/

**Comment by GhazalehManj** [comment]
Done!

**Comment by GhazalehManj** [comment]
closed issue

**Comment by GhazalehManj** [comment]
Done.
