### ISSUE TITLE
[BUG] qsirecon 2 (i.e. enigma dti participant) not robust to many study schemes

### ISSUE THREAD

**Issue by edickie** [TIGRLab/SCanD_project#56]
In my test run of qsirecon 2, it failed because the dwi filenames had "run" in them. 

I also suspect (from reading the script) that the script would fail for cross sectional studies (with no session id).

We might need to recode the file finding in python using pybids?

**Comment by GhazalehManj** [comment]
Why did you change qsiprep container to enigma in qsirecon step2?

**Comment by GhazalehManj** [comment]
I see, I'll edit the code.

**Comment by GhazalehManj** [comment]
Erin, Would you please send me an example of your file names that gave error?
I've previously editted the original code for different conditions. Just wondering what else I should consider.

**Comment by GhazalehManj** [comment]
Done. I added multiple conditions to capture "run" and "acquisition". About session, all scans (longitudinal, cross-sectional) have session part, right?

**Comment by edickie** [comment]
In the BIDS spec, cross-sectional projects can exist without sessions - (i,e. func and anat folder appear directly under teh subjects folder) (an example here: https://openneuro.org/datasets/ds001132/versions/1.0.0 Most of the labs data is longitudinal (or we add session for no reason). But our pipelines should be able to work with either version.

**Comment by GhazalehManj** [comment]
Done!
