### ISSUE TITLE
[BUG]ish Don't hard code spatial resolution in qsiprep scripts 

### ISSUE THREAD

**Issue by edickie** [TIGRLab/SCanD_project#98]
The qsiprep scripts writting with an output resolution of 1.7 - which is specific for most of our newer CAMH studies, but might not be appropriate for all DWI in SCaN-D.

The general approach we have used is to match teh output resolution to the input resolution of the DWI files (which is 1.7 for ABCD style DWI). 

We probably need a little utility that figures out the input resolution of the raw DWI images so we can set the output resolution to match.

**Comment by GhazalehManj** [comment]
I added a piece of code in qsiprep to get the input dwi dimension and use it in the output resolution. Also, added the code to setup (00_) to install afni for "3dinfo".
